### ISSUE TITLE
A little minor problem

### ISSUE THREAD

**Issue by jackalcooper** [jhartwell/Plsm#10]
I got `** (Mix) The task "plsm.config" could not be found` and `** (Mix) The task "plsm" could not be found` when running the mix task in a sub directory rather than the root directory of my mix project. You said `The model files are generated in the folder that you are running from.` so I'm not sure it's a bug or I misunderstood.

**Comment by jackalcooper** [comment]
If we can't run it in a sub directory, would it be better to specify a destination directory?

**Comment by jhartwell** [comment]
@jackalcooper I added the ability to specify destination directory. It is the destination property on plasm.config. You will have to pull from the new branch add-destination-config as I don't want to put this into master until I know it works. It works on windows but not sure how other systems will be affected

**Comment by jhartwell** [comment]
@jackalcooper  This is what your project config should look like if you want to add a destination

project = [
			name: "Plsm",
			destination: "C:\\Bk\\"
		  ]

**Comment by jackalcooper** [comment]
@jhartwell Thanks!
