### ISSUE TITLE
Phoenix 1.4, generated schemas contain wrong syntax

### ISSUE THREAD

**Issue by MathiasWedeken** [jhartwell/Plsm#100]
When following the guidelines, the generated schemas contain field definitions with the :primary_key atom, like this: 

`field :created_date, :naive_datetime, :primary_key false`

Which doesn't compile. What does compile is 

`field :created_date, :naive_datetime,  primary_key: false` 

Although I have no idea if that was the intended output- I have never seen schemas with `primary_key: false` on all their fields.

**Comment by jhartwell** [comment]
@MathiasWedeken thanks for letting me know. I will look into this and make necessary changes

**Comment by jhartwell** [comment]
@MathiasWedeken, @sashman has created a fix for this that has been merged in. You can use the following for in your mix.exs to pull in these changes:

`{:plsm, git: "https://github.com/jhartwell/plsm.git", branch: "master"}`

I have an update that will remove the primary_key field when the column is not a primary key coming up but @sashman's change will at least fix this temporarily
