### ISSUE TITLE
the generated config and the generated schemas had syntax issues or things missing

### ISSUE THREAD

**Issue by DEvil0000** [jhartwell/Plsm#112]
when trying this I used it with maria DB.
the generated separate config file had the use line missing `use Mix.Config`.
the generated schema files messed up the primary_key option (which should be done differently anyway).
however it should be `primary_key: false` not `:primary_key false`

**Comment by 9to1url** [comment]
Yes, I also encountered this issue.
Smallint column not generated in schema but does shows up on changeset.

**Comment by jhartwell** [comment]
@DEvil0000 The primary key issue and the missing `use Mix.Config` issues have been fixed.

@9to1url the issue with smallint has been fixed as well. 

Both those fixes are in version 2.4.0. Please let me know if you have any other issues.
