### ISSUE TITLE
Add primary key support to Postgres

### ISSUE THREAD

**Issue by jhartwell** [jhartwell/Plsm#19]
Currently the postgres implementation does not have primary key functionality. This should be added to coincide with the MySql changes

**Comment by luizvarela** [comment]
Hey, jus to let you know, I already working on that.

**Comment by jhartwell** [comment]
@luizvarela I know. I just wanted to make a ticket for it. Are you able to assign it to yourself?

**Comment by luizvarela** [comment]
@jhartwell I not able to assign to me, I think I don't have permissions.

**Comment by jhartwell** [comment]
@luizvarela I removed the help wanted. I'm unable to assign to you either but I don't believe there is anybody else working on this other than us

**Comment by luizvarela** [comment]
It's assigned now, thanks :+1:

**Comment by luizvarela** [comment]
Issue was already merged to master in https://github.com/jhartwell/Plsm/pull/22
