### ISSUE TITLE
no postgre config information

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [jhartwell/Plsm#24]
Hi. I see in plsm code that there is case: 
```
 case configs.database[:type] do
      :mysql -> IO.puts "Using MySql..."; Plsm.Database.create %Plsm.Database.MySql{}, configs
      :postgres -> IO.puts "Using PostgreSQL..."; Plsm.Database.create %Plsm.Database.PostgreSQL{}, configs
      _ -> IO.puts "Using default database MySql..."; Plsm.Database.create %Plsm.Database.MySql{}, configs
    end
```
but I can't find any documentation about that. How I can use plsm for postgres ? 
Add type: "postgres" or type: :postgres to Plsm.config wont work.

**Comment by jhartwell** [comment]
@the-man-with-a-golden-mind I will take a look at this and let you know. I will also update the docs to make it clearer

**Comment by jhartwell** [comment]
@the-man-with-a-golden-mind when you say "it won't work" does it give you an error message or some other type of message? If so, could you please post it. If not, well that is a problem and there should be an error message and that would be another issue that needs opening.

**Comment by jhartwell** [comment]
@the-man-with-a-golden-mind also, could you share your plsm.configs file? Please don't forget to scrub sensitive information before uploading

**Comment by joshuataylor** [comment]
It's because when setting the type to "postgres", in `plsm.ex` when checking that `configs.database[:type]` is either `:postgres` or `:mysql`, neither will work as it is a string, not an atom.

```
    case configs.database[:type] do
      :mysql -> IO.puts "Using MySql..."; Plsm.Database.create %Plsm.Database.MySql{}, configs
      :postgres -> IO.puts "Using PostgreSQL..."; Plsm.Database.create %Plsm.Database.PostgreSQL{}, configs
      _ -> IO.puts "Using default database MySql..."; Plsm.Database.create %Plsm.Database.MySql{}, configs
    end
```

**Comment by jhartwell** [comment]
@the-man-with-a-golden-mind are you still having an issue with this?

**Comment by jhartwell** [comment]
@the-man-with-a-golden-mind, since there has been no response I am going to close this ticket. Please re-open if this issue is still persisting.
