### ISSUE TITLE
Could use config.exs (ie dev.exs) for the config instead of creating a config file?

### ISSUE THREAD

**Issue by joshuataylor** [jhartwell/Plsm#36]
When using ecto, the application will require the following setup done anyway, for example in `dev.exs`:
```
config :foobar, Foobar.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "example",
  password: "example",
  database: "foobar",
  hostname: "127.0.0.1",
  port: 5432
```

As you can see, all the options for database config will already be set here, and if options aren't set (ie port), we could assume that they are the defaults. We could read these settings.

Alternatively, we could use the config.exs instead of creating a Plsm.configs, as this is the "standard" way Elixir does things.

Up to you of course, but would love some discussion around this.

**Comment by jhartwell** [comment]
When I started this project I had about 2 weeks of Elixir experience (if that) so I definitely didn't do this the "elixir way". Moving this to a more proper "Elixir way" of doing things makes a lot of sense and can only help the project. That being said, it is going to be important to maintain backward compatbility with the old config files. Going forward there may not be any new changes to generating the config file but we should always be able to read it (at least 'til version 2.0)

**Comment by joshuataylor** [comment]
Heh, well this project is awesome, my own implementation ages ago that I wrote as a hack imported from Postgres via functions, so this is really good :) (I've since lost this, thankfully :)).

Yeah, keeping both ways (when implemented) until some arbitrary point (as you said, 2.0 or whatever) is a great option.

**Comment by jhartwell** [comment]
Thanks, I'm glad you feel that way! I'll start moving to the config.exs file and away from the custom config file

**Comment by jhartwell** [comment]
This is in version 2.0.0
