### ISSUE TITLE
Add foreign key support

### ISSUE THREAD

**Issue by jhartwell** [jhartwell/Plsm#4]
We need to be able to find the foreign keys and make the belongs_to association. It is undecided what we should do for the referenced table as it could be has_one or has_many and it is something we may not be able to deduce from the table

**Comment by the-man-with-a-golden-mind** [comment]
Sql is quite simple:
`SELECT DISTINCT
        a.attname as column_name, 
        format_type(a.atttypid, a.atttypmod) as data_type,
        coalesce(i.indisprimary,false) as primary_key, 
        f.references_table as foreign_table,
        f.references_field as foreigh_field,
        a.attnum as num 
      FROM pg_attribute a  
      JOIN pg_class pgc ON pgc.oid = a.attrelid 
      left JOIN (
		SELECT 
		tc.table_name as table,
		kcu.column_name as field,
		ccu.table_name AS references_table,
		ccu.column_name AS references_field
		FROM information_schema.table_constraints tc

		LEFT JOIN information_schema.key_column_usage kcu
		ON tc.constraint_catalog = kcu.constraint_catalog
		AND tc.constraint_schema = kcu.constraint_schema
		AND tc.constraint_name = kcu.constraint_name

		LEFT JOIN information_schema.referential_constraints rc
		ON tc.constraint_catalog = rc.constraint_catalog
		AND tc.constraint_schema = rc.constraint_schema
		AND tc.constraint_name = rc.constraint_name

		LEFT JOIN information_schema.constraint_column_usage ccu
		ON rc.unique_constraint_catalog = ccu.constraint_catalog
		AND rc.unique_constraint_schema = ccu.constraint_schema
		AND rc.unique_constraint_name = ccu.constraint_name

		WHERE lower(tc.constraint_type) in ('foreign key') 
      ) as f on a.attname = f.field
      LEFT JOIN pg_index i ON  
          (pgc.oid = i.indrelid AND i.indkey[0] = a.attnum) 
      WHERE a.attnum > 0 AND pgc.oid = a.attrelid 
      AND pg_table_is_visible(pgc.oid) 
      AND NOT a.attisdropped 
      AND pgc.relname = '#{table}' 
      ORDER BY a.attnum;`

...but it takes some time. 

For ECTO typical belongs_to looks like "belongs_to :<plural_table_name>, <our_project>.<moduleName>" so we need some simple name converters and...project name (maybe as a enviroment var or flag? ).
I will try to inject those ideas to plsm code (is quite simple and well written :) ).

**Comment by jhartwell** [comment]
@the-man-with-a-golden-mind when you say it takes some time, how much time? Remember, this should only be run once per project as any other changes could be done by hand after the initial model. While waiting sucks, a little delay to get correct information is ok with me.

Do you know that your query works on the last few versions of Postgre?

**Comment by joshuataylor** [comment]
That query doesn't return anything for me on Postgres 9.6.

**Comment by joshuataylor** [comment]
Having a crack at this, as my current project will use this, and will save everyone a lot of time going forward.

The above query (thank you, by the way!) Adds about 600ms-800ms for me (on my outdated laptop), with about 30 tables, going from 0.7s to 1.4s. That's acceptable IMHO, as you said it's not run very often.

**Comment by tslater** [comment]
@joshuataylor do you have a fork I could try?

**Comment by jhartwell** [comment]
@tslater the postgre foreign key code is in version 2.0 of Plsm. You can go ahead and pull it from Hex and use it

**Comment by tslater** [comment]
@jhartwell That's good to know. I am actually wanting this for MySQL. I'm much more familiar with MySQL, so looking through the Postgresql query, with it's arrays, has been tough. Anyway, I thought I'd take a stab at a query for MySQL. As I got going on it, I realized the arrays are probably there because you can have multiple keys (ex. primary key and foreign key) on a column, but we're trying to return only one row per column. My solution is probably not robust and might be overlooking some cases, but trying to match the results of the postgresql query, I came up with this:
```
SELECT DISTINCT 
	isc.COLUMN_NAME, 
	MAX(isc.DATA_TYPE), 
	IF(MAX(isc.COLUMN_KEY)="PRI", "TRUE", "FALSE") as PRIMARY_KEY,
	MAX(REFERENCED_TABLE_NAME),
	MAX(REFERENCED_COLUMN_NAME),
	MAX(isc.ORDINAL_POSITION) as NUM
FROM INFORMATION_SCHEMA.COLUMNS isc
LEFT JOIN  INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
ON 
	isc.TABLE_NAME=kcu.TABLE_NAME
	 AND isc.TABLE_SCHEMA = kcu.CONSTRAINT_SCHEMA
	 AND isc.COLUMN_NAME = kcu.COLUMN_NAME 
WHERE isc.`TABLE_SCHEMA` = 'cephas' AND isc.`TABLE_NAME` = 'quiz_comment'
GROUP BY ISC.COLUMN_NAME
ORDER BY MAX(isc.ORDINAL_POSITION)
```

**Comment by tslater** [comment]
I put this query in, with some success. There is a PR /\ with my progress so far.

**Comment by jhartwell** [comment]
This has been partially implemented so this ticket will be closed. There may need to be two new tickets, one for MySQL and one from Postgres to make updates to the foreign key info but it would also be helpful to have test data to be able to easily test
