### ISSUE TITLE
Add Postgres Support

### ISSUE THREAD

**Issue by jhartwell** [jhartwell/Plsm#5]
Currently only MySql is supported and we need to expand that.  We should use the ODBC drivers so we can easily resuse code as well as just needed the same type of driver for each database

**Comment by luizvarela** [comment]
Postgrex can be used to implement the PostgreSQL support
https://github.com/elixir-ecto/postgrex
I will try to implement a start point.

**Comment by jhartwell** [comment]
@luizvarela yes, postgrex is possible. When I made the ticket it was only ODBC, which would make it more difficult (to an extent). Hopefully my code is decent enough for a good starting point that you can understand

**Comment by jhartwell** [comment]
@luizvarela has added this support into master.
