### ISSUE TITLE
Receiving Argument Error message when trying to run mix PLSM

### ISSUE THREAD

**Issue by sqlasylum** [jhartwell/Plsm#68]
I was attempting to use PLSM(master branch) this evening for a Elixir project I am working on.  I was trying to generate models from my PostgresDB but can't seem to get past this error message that PLSM is putting out.  

 I've attached the output of it below. 

 I added an       "  |> IO.inspect()" the line before the error so I could try and see what was failing. I've also added my config that I'm using.   

using elixir 1.5.2

config

config :plsm,
 module_name: "test",
 destination: "outputpath",
 server: "localhost",
 port: "5432",
 database_name: "friends",
 username: "postgres",
 password: nil,
 type: :postgres

--execution
$ mix plsm

Compiling 1 file (.ex)

Using PostgreSQL...

["defmodule test.SchemaMigrations do\n  use Ecto.Schema\n\n@primary_key {:version, :integer, []}\n  schema \"schema_migrations\" do\n    field :version, :integer\n    field :inserted_at, Ecto.DateTime\n\n  end\n  def changeset(struct, params \\\\ %{}) do\n    struct\n    |> cast(params, :version, :inserted_at)\n  end\nend\n",

 "defmodule test.Organizations do\n  use Ecto.Schema\n\n  schema \"organizations\" do\n    field :id, :integer\n    field: business_name, :text\n    field: address, :text\n    field :created_at, Ecto.DateTime\n    field :updated_at, Ecto.DateTime\n    field: thank_you_content, :text\n    field: business_name_slug, :text\n    field :monthly_organization_review_quota, :integer\n    field :locations_count, :integer\n    field :review_invitations_count, :integer\n    field :partner_id, :integer\n    field :location_limit, :integer\n    field: default_password, :text\n    field :client_success_id, :integer\n    field: logo, :text\n    field: first_day_of_week, :text\n    field :facebook_enabled_at, Ecto.DateTime\n    field :all_locations_mode_enabled_at, Ecto.DateTime\n    field :kafka_enabled_at, Ecto.DateTime\n    field :all_locations_view_enabled_at, Ecto.DateTime\n\n  end\n  def changeset(struct, params \\\\ %{}) do\n    struct\n    |> cast(params, :id, :business_name, :address, :active, :created_at, :updated_at, :thank_you_content, :business_name_slug, :send_welcome_email, :monthly_organization_review_quota, :archived, :direct_review, :test, :locations_count, :review_invitations_count, :partner_id, :use_org_name_in_cobra, :invitation_csv_report_enabled, :location_limit, :bulk_user_upload_enabled, :bulk_invite_upload_enabled, :default_password, :text_analytics_reporting_enabled, :client_success_id, :logo, :first_day_of_week, :facebook_enabled_at, :all_locations_mode_enabled_at, :kafka_enabled_at, :all_locations_view_enabled_at)\n  end\nend\n",

 "defmodule test.Products do\n  use Ecto.Schema\n\n  schema \"products\" do\n    field :id, :integer\n    field: name, :text\n\n  end\n  def changeset(struct, params \\\\ %{}) do\n    struct\n    |> cast(params, :id, :name)\n  end\nend\n",

 "defmodule test.People do\n  use Ecto.Schema\n\n  schema \"people\" do\n    field :id, :integer\n    field: first_name, :text\n    field: last_name, :text\n    field :age, :integer\n\n  end\n  def changeset(struct, params \\\\ %{}) do\n    struct\n    |> cast(params, :id, :first_name, :last_name, :age)\n  end\nend\n"]

** (ArgumentError) argument error

    :erlang.apply("defmodule test.SchemaMigrations do\n  use Ecto.Schema\n\n@primary_key {:version, :integer, []}\n  schema \"schema_migrations\" do\n    field :version, :integer\n    field :inserted_at, Ecto.DateTime\n\n  end\n  def changeset(struct, params \\\\ %{}) do\n    struct\n    |> cast(params, :version, :inserted_at)\n  end\nend\n", :name, [])

    lib/plsm.ex:19: anonymous fn/2 in Mix.Tasks.Plsm.run/1

    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2

    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3

    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2

**Comment by jhartwell** [comment]
@sqlasylum What line did you put the IO.inspect and which file?

**Comment by kwokster10** [comment]
@jhartwell I am also seeing this error when running with Postgres:
```
mix plsm
Using PostgreSQL...
** (ArgumentError) argument error
    :erlang.apply("defmodule Database.ActiveAdminComments do\n  use Ecto.Schema\n\n  schema \"active_admin_comments\" do\n    field :id, :integer\n    field: namespace, :text\n    field: body, :text\n    field: resource_id, :text\n    field: resource_type, :text\n    field :author_id, :integer\n    field: author_type, :text\n    field :created_at, :naive_datetime\n    field :updated_at, :naive_datetime\n\n  end\n  def changeset(struct, params \\\\ %{}) do\n    struct\n    |> cast(params, :id, :namespace, :body, :resource_id, :resource_type, :author_id, :author_type, :created_at, :updated_at)\n  end\nend\n", :name, [])
    lib/plsm.ex:18: anonymous fn/2 in Mix.Tasks.Plsm.run/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by jhartwell** [comment]
@kwokster10 I'm looking into this now and will provide an update when I have one.

**Comment by jhartwell** [comment]
@kwokster10  @sqlasylum , I have pushed a fix to develop and have tested it on Postgres. I am in the process of testing now for MySQL and then I will push this update to master and hex.

**Comment by jhartwell** [comment]
@sqlasylum @kwokster10  This has been fixed and is in hex. You can go ahead and pull down 2.2.1 from hex using {:plsm, "~> 2.2"} in your mix.exs deps function

**Comment by kwokster10** [comment]
@jhartwell Thank you for the quick turnaround. I will check it out now.

**Comment by sqlasylum** [comment]
Thanks as well @jhartwell  I went another route but will pull down the fix and use this for a future project.
