### ISSUE TITLE
I got this when I run mix plasm

### ISSUE THREAD

**Issue by jackalcooper** [jhartwell/Plsm#7]
```
jackalcooper@Jackals-Mac ~/e/subway> mix plasm
No database type passed in. Defaulting to MySql
** (UndefinedFunctionError) function :odbc.start/0 is undefined (module :odbc is not available)
    :odbc.start()
    lib/database/common.ex:4: Plasm.Database.Common.connect/1
    lib/plasm.ex:30: Mix.Tasks.Plasm.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

```

**Comment by renews** [comment]
Same here, my plasm.configs is right btw.

**Comment by jhartwell** [comment]
do you have erlang installed? If so, which version?

**Comment by renews** [comment]
@jhartwell Yes version 19.2(MacOS), and btw, i added `type: :mysql`  to the end of database list, so it does not show 

> No database type passed in. Defaulting to MySql,

Now it shows

`MySql database selected
** (UndefinedFunctionError) function :odbc.start/0 is undefined (module :odbc is not available)
    :odbc.start()
    lib/database/common.ex:4: Plasm.Database.Common.connect/1
    lib/plasm.ex:30: Mix.Tasks.Plasm.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2`

**Comment by jhartwell** [comment]
Ok, I'll take a look now and let you know what I find

**Comment by jhartwell** [comment]
It appears that you need to also install erlang-odbc module. I'm looking up the best way to do that and will post it here

**Comment by jhartwell** [comment]
Real quick, did you compile erlang yourself or did you get pre-made binaries?

**Comment by renews** [comment]
@jhartwell brew :)

**Comment by jhartwell** [comment]
Looks like this is a known issue with brew (https://github.com/Homebrew/legacy-homebrew/issues/38845) is it possible to either try macports or compile from source?

**Comment by jhartwell** [comment]
It appears that on OS X Erlang is hard coded to use iodbc. Do you have that installed? If not, could you please install it and try again?

**Comment by jhartwell** [comment]
@renews @jackalcooper  still having this issue?

**Comment by jackalcooper** [comment]
@jhartwell Sorry Jonathan I only know Elixir and I'm a lazy Mac user so I didn't try to do it last time because it seems to be something rather deep and complicated. But I have more time this weekend so I'm going to examine it for you. I will let you know the outcome later.

**Comment by jackalcooper** [comment]
@jhartwell Here comes the new error:
```
mix plasm
No database type passed in. Defaulting to MySql
Error: [unixODBC][Driver Manager]Can't open lib 'MySQL ODBC 5.3 UNICODE Driver' : file not found SQLSTATE IS: 01000 Connection to database failed.
```

**Comment by jhartwell** [comment]
Do you have the MySql ODBC driver? What version of the driver are you using? 5.3 corresponds to the latest version of the MySql ODBC driver

**Comment by jhartwell** [comment]
@jackalcooper I have a fix going in today that is going to remove dependency on odbc so this issue will be resolved.

**Comment by jackalcooper** [comment]
@jhartwell Thanks Jonathan! It's working!
