### ISSUE TITLE
[CompileError] Typo with module names

### ISSUE THREAD

**Issue by luizvarela** [jhartwell/Plsm#8]
I started sketching some code to use PostgreSQL and if try to compile you'll get a compile error. That seems caused by the last commit.
https://github.com/jhartwell/Plsm/commit/ed70d2372fffc128b680bbb1cc17ecb144408b4b
```
** (CompileError) lib/plsm.ex:14: Plsm.Database.MySql.__struct__/1 is undefined, cannot expand struct Plsm.Database.MySql
```

**Comment by jhartwell** [comment]
@luizvarela I will fix this today. I changed the name of the project to Plsm to differentiate from the other Elixir libraries of the same name. I have a commit to remove odbc use coming in today and that will fix it

**Comment by luizvarela** [comment]
@jhartwell Great, I will wait for the changes.

**Comment by jhartwell** [comment]
@luizvarela have you made any code changes yet? I have a fix that will change the way the program is coded but I don't want to make you re-write stuff so I can wait for your change to go in before I make my breaking changes if you've started

**Comment by luizvarela** [comment]
Not yet, you can send your changes :)

**Comment by jhartwell** [comment]
@luizvarela I have fixed the module name issue. If you decide to go the route of adding postgres support, I suggest you use a library instead of ODBC as I'm working on removing ODBC code. Also, note that the protocol for Database may change shortly

**Comment by jhartwell** [comment]
@luizvarela MySql changes have been made and everything seems to be working. Feel free to add Postgres support!
