### ISSUE TITLE
CamelCase Table Names are converted to Module Names with only the first letter capitalized

### ISSUE THREAD

**Issue by cdesch** [jhartwell/Plsm#80]
Table names like `MyAwesomeTable` are converted to module names like `MyApp.MyNameSpace.Myawesometable` as Plsm assume that the table name must be snake case `my_awesome_table`. Plsm should convert these table names with CamelCase to module names with respective camel case like this. `MyApp.MyNameSpace.MyAwesomeTable`

I'll submit a PR

**Comment by jhartwell** [comment]
@cdesch sounds good, I'll look out for the PR. Please make sure you are merging into develop

**Comment by cdesch** [comment]
@jhartwell Okay. Pushing the changes into develop. I just pulled the latest `develop` into my merge.

**Comment by jhartwell** [comment]
@cdesch , looks good, this has been merged into develop. Thanks!
