### ISSUE TITLE
they may contain sensitive data such as database credentials

### ISSUE THREAD

**Issue by codenoid** [jhartwell/Plsm#89]
** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as                     
they may contain sensitive data such as database credentials.

    :erlang.binary_to_integer/1
    lib/mariaex/protocol.ex:160: Mariaex.Protocol.normalize_port/1
    (elixir) lib/keyword.ex:832: Keyword.update!/4
    (elixir) lib/keyword.ex:836: Keyword.update!/4
    lib/mariaex/protocol.ex:72: Mariaex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mariaex.Protocol
** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

        :erlang.binary_to_integer/1
        lib/mariaex/protocol.ex:160: Mariaex.Protocol.normalize_port/1
        (elixir) lib/keyword.ex:832: Keyword.update!/4
        (elixir) lib/keyword.ex:836: Keyword.update!/4
        lib/mariaex/protocol.ex:72: Mariaex.Protocol.connect/1
        (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by jhartwell** [comment]
@codenoid what does your config file look like. Please scrub the identifying data (host, username, password)

**Comment by jhartwell** [comment]
Closing due to lack of response.
