### ISSUE TITLE
Mariaex Version Upgrade

### ISSUE THREAD

**Issue by rokobasilisk** [jhartwell/Plsm#91]
Hi there, thanks for this great library. When I try use it in a new Phoenix project I get a dependency mismatch issue. 

I was wondering if it would be possible to upgrade the Mariaex dependency to 0.9.1.
I am totally new to Phoenix and Elixir so happy to open a PR, but feel it might be safer if an experienced person updates it.

**Comment by jhartwell** [comment]
I will update this in the next few days. I am add some testing changes as well so that I can be sure that this upgrade doesn't break anything,  which is why it will be longer than a quick fix

**Comment by jhartwell** [comment]
@rokobasilisk I have updated the dependencies on mariaex and postgrex and checked them in. I will be adding testing before creating a new version on hex so in the meantime you can put the following in your deps 

`{:plsm, github: "jhartwell/Plsm"}`


I will comment on this issue again once the new version has been pushed to hex

**Comment by rokobasilisk** [comment]
@jhartwell huge thanks for this. Hopefully when I have a bit more experience in Elixir I will be able to contribute.

**Comment by sashman** [comment]
Hey @rokobasilisk @jhartwell any update on this?

**Comment by jhartwell** [comment]
@sashman sorry, I have been busy and haven't gotten much time to play with docker and automated DB testing. As stated above, you can reference the latest version by using 

`{:plsm, github: "jhartwell/Plsm"}`

I will work on getting a new release out with this change today, though it won't be tested.

**Comment by sashman** [comment]
awsome, thanks @jhartwell!

**Comment by jhartwell** [comment]
@sashman @rokobasilisk a new version has been published to hex with this change.
