### ISSUE TITLE
Fix cast call

### ISSUE THREAD

**Issue by sashman** [jhartwell/Plsm#93]
The generated schema file [creates](https://github.com/jhartwell/Plsm/blob/257145cc91b1d43c8c8e2b85974fb0299ad3c1bd/lib/io/export.ex#L91):

```
|> cast(params, :a, :b, :c)
```

While the [current API](https://hexdocs.pm/ecto/Ecto.Schema.html#embeds_many/3-inline-embedded-schema) requires:

```
|> cast(params, [:a, :b, :c])
```

Also, an import is needed:

```
import Ecto.Changeset
```

I can knock up a quick PR for this if you want?

**Comment by sashman** [comment]
@jhartwell this is a breaking change introduced in Ecto 3 I think. PR coming up!

**Comment by sashman** [comment]
@jhartwell any feedback on the PR?

**Comment by jhartwell** [comment]
@sashman sorry about that, I have made a comment on the PR
