### ISSUE TITLE
Primary keys, eg :id, clash with auto-generated Ecto primary keys

### ISSUE THREAD

**Issue by sashman** [jhartwell/Plsm#95]
This is a two-parter, in the first case by default every `:id` field clashes with the [autogenerated field](https://hexdocs.pm/ecto/Ecto.Schema.html#module-example). From docs:

> By default, a schema will automatically generate a primary key which is named id and of type :integer.

I fixed this for my case by creating a local Schem module:

```elixir
defmodule My.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      @primary_key false
    end
  end
end
```

This turns the autogeneration off, in addition all of the generated schemas need to use `My.Schema`.

The second part is the primary keys that aren't called `:id` have the primary key override with `@primary_key` setting. I had to manually delete those in order to compile.

**Comment by jhartwell** [comment]
@sashman I apologize for missing this issue. I will look into this

**Comment by jhartwell** [comment]
@sashman After thinking about it, I am going to change primary keys to be part of the field/3 instead of `@primary_key`. I believe that should fix both issues

**Comment by sashman** [comment]
No probs @jhartwell, and thanks for being awesome 👍

**Comment by jhartwell** [comment]
@sashman This has been merged to master
