### ISSUE TITLE
Some minor nits with Phoenix 1.4.10 and Elixir 1.9

### ISSUE THREAD

**Issue by rugyoga** [jhartwell/Plsm#97]
I ended up writing the following post-processing script to fix them:

https://gist.github.com/rugyoga/1ab523d2d6988afb0bff77e649dbf66b

Two are the same issues as @sashman has reported.

**Comment by jhartwell** [comment]
Thanks @rugyoga I think I may add some post processing tasks as well, such as singularizing modules
